# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(06dcc3e1-fca7-4757-a22d-37e528e2e8c8)'
        azureContainerRegistry: '{"loginServer":"prc301.azurecr.io", "id" : "/subscriptions/06dcc3e1-fca7-4757-a22d-37e528e2e8c8/resourceGroups/homeworkprc/providers/Microsoft.ContainerRegistry/registries/prc301"}'
        dockerComposeFile: '**/docker-compose.yml'
        additionalDockerComposeFiles: 'docker-compose.override.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
        nopIfNoDockerComposeFile: true
        requireAdditionalDockerComposeFiles: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(06dcc3e1-fca7-4757-a22d-37e528e2e8c8)'
        azureContainerRegistry: '{"loginServer":"prc301.azurecr.io", "id" : "/subscriptions/06dcc3e1-fca7-4757-a22d-37e528e2e8c8/resourceGroups/homeworkprc/providers/Microsoft.ContainerRegistry/registries/prc301"}'
        dockerComposeFile: '**/docker-compose.yml'
        additionalDockerComposeFiles: 'docker-compose.override.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'push'
        nopIfNoDockerComposeFile: true
        requireAdditionalDockerComposeFiles: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'docker-compose'
        publishLocation: 'Container'
